### ISSUE TITLE
Alterar o retorno do BipBopValidator para uma entidade com getters/setters

### ISSUE THREAD

**Issue by eduardogalbiati** [helsinque/cpf_cnpj#6]
Para tornar claro para o desenvolvedor quais campos serão retornados da chamada de API do BipBop e unificar o retorno em uma Entidade

**Comment by helsinque** [comment]
Neste ponto Edu irai até comentar que acredito que fica mais simples e direto ter a tratativa de exception uma camada antes, pois desta forma podemos utilizar de forma direta tendo acesso direto ao retorno, Assim com os outros validadores.

Tipo na utilização $cnpj->validate();

Sem precisa ter um try.

**Comment by eduardogalbiati** [comment]
Inicialmente eu achei que a BipBop iria retornar todos os dados do cnpj, agora que entendi que ele checa se o número é verdadeiro ou não....massa.....realmente a entidade não faz sentido, só faria se retornasse bastante info

O try/catch vem do costume de consumir uma lib, mas realmente nesse caso existe um pattern interessante descrito pelo Martin Fowler, justamente sobre validadores....o notification
https://martinfowler.com/articles/replaceThrowWithNotification.html

Acredito que essa seja a melhor saída possível, pelo menos a mais elegante
