### ISSUE TITLE
Dúvida referente ao BipBopValidator

### ISSUE THREAD

**Issue by eduardogalbiati** [helsinque/cpf_cnpj#7]
Será que ele realmente é um validator? me parece que ele possui uma responsabilidade maior de retornar os dados a partir de um CPF/CNPJ, não me parece que ele deveria ser tratado como validator.

Atualmente quando precisamos validar um CPF/CNPJ usamos o seguinte código
`$validate = new Validate();`
`$return=  $validate->validate("Cnpj", $document);`

Para a bipbop, sugiro uma mudança
`$validate = new Validate();`
`$return=  $validate->getInfo("Cnpj", $document);`

Com essa mudança, não faz muito sentido o Validate() buscar a Info, com isso podemos mudar o nome new Validate para outra coisa, e utilizar esse mesmo nome no Repositório. Este nome seria o nome oficial da biblioteca.

**Comment by eduardogalbiati** [comment]
O BipBop API não é um validator, portanto precisa criar um outra pasta para ele, uma nova factory e uma nova interface. São responsabilidades distintas, uma coisa é validar outra coisa é retornar informações sobre.

Lembrando que no refactor, a dependencia WebService deve ser injetada no constructor pela factory, para que possamos mockar ela nos testes unitários, de resto a estrutura será bem semelhante aos validadores

**Comment by helsinque** [comment]
Na verdade Edu vejo como uma validação no orgão RFB pois tesmos a validação segundo uma regra básica, objetivo de utilizar a Bipbop é ter a possibilidade de validar se de fato existe o cadastro do mesmo de uma forma ágil e rápida, sem trazer muitas informações sobre o documento, mais a Bipbop fornece de fato muitas informações sobre um documento, porém através de outras requisições, acho que esta bacana bem simples o validador.
O que acha?
